name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - LICENSE

env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Xcode build
        run: set -o pipefail \
             && xcodebuild \
             -sdk iphonesimulator \
             -configuration Debug \
             -project Versatile.xcodeproj \
             -scheme Versatile \
             -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.4' \
             build

  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Xcode test
        run: set -o pipefail \
             xcodebuild \
             -sdk iphonesimulator \
             -configuration Debug \
             -project Versatile.xcodeproj \
             -scheme Versatile \
             -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.4' \
             -skip-testing:VersatileUITests \  
             clean test

  info:
    runs-on: macOS-latest

    steps:
      - name: Show Xcode version
        run: xcodebuild -version

      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'

      - name: Show devices
        run: xcrun xctrace list devices
